anki_web/cards/urls.py
from django.urls import path
from anki_web.cards import views

app_name = 'cards'
urlpatterns = [
    path('<int:pk>/update/', views.UpdateCardView.as_view(), name='update'),
    path('delete/', views.DeleteAllCardsView.as_view(), name='delete_all'),
    path('<int:pk>/delete/', views.DeleteCardView.as_view(), name='delete'),
    path('<int:card_id>/answer/', views.check_answer, name='answer'),
    path('<int:pk>', views.DetailCardView.as_view(), name='show_card'),
    path('all/', views.AllCardsView.as_view(), name='all_cards'),
    path('select/', views.delete_select_cards, name='select'),
    path('<download/', views.download_file, name='download')
]

anki_web/decks/urls.py
from django.urls import path, include
from anki_web.decks import views
from anki_web.cards.views import (
    CreateCardView,
    ListCardsView,
    upload_file,
    ListCardsDayView,
    show_answer,
    delete_select_cards,
    DeleteAllCardsView,
    download_file
)

app_name = 'decks'
urlpatterns = [
    path('', views.ListDecksView.as_view(), name='decks'),
    path('create/', views.CreateDeckView.as_view(), name='create'),
    path('<int:pk>/delete/', views.DeleteDeckView.as_view(), name='delete'),
    path('<int:pk>/', include('anki_web.cards.urls')),
    path('<int:pk>/select/', delete_select_cards, name='select'),
    path('<int:pk>/delete_all_cards/', DeleteAllCardsView.as_view(), name='delete_all'),
    path('<int:pk>/create/', CreateCardView.as_view(), name='create_card'),
    path('<int:pk>/upload/', upload_file, name='upload'),
    path('<int:pk>/cards/', ListCardsView.as_view(), name='cards'),
    path('<int:pk>/learn/', ListCardsDayView.as_view(), name='learn'),
    path('<int:card_id>/answer/', show_answer, name='answer'),
    path('<int:pk>/download/', download_file, name='download')
]

anki_web/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth.views import LogoutView
from anki_web import views
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('anki_web.anki_api.urls')),
    path('', views.MainPageView.as_view(), name='main_page'),
    path('login/', views.LoginUserView.as_view(next_page='main_page'), name='login'),
    path('logout/', LogoutView.as_view(next_page='main_page'), name='logout'),
    path('password_reset/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('password_reset_done/', views.ResetPasswordDoneView.as_view(),
         name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', views.ResetPasswordConfirmView.as_view(),
         name='password_reset_confirm'
         ),
    path('password_reset_complete/', views.ResetPasswordCompleteView.as_view(),
         name='password_reset_complete'),
    path('users/', include('anki_web.users.urls')),
    path('decks/', include('anki_web.decks.urls')),
    path('cards/', include('anki_web.cards.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$',
            schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger',
            cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc',
            cache_timeout=0), name='schema-redoc'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

anki_web/users/urls.py
from django.urls import path
from anki_web.users import views

urlpatterns = [
    path('', views.CreateUserView.as_view(), name='create'),
    path('user/', views.show_user, name='show_user'),
    path('<int:pk>/update/', views.UpdateUserInfoView.as_view(), name='update'),
    path('change_password/', views.change_password, name='password'),
    path('<int:pk>/add_email/', views.AddEmailView.as_view(), name='add_email'),
    path('activate_email/<uidb64>/<token>/',
         views.activate_email, name='activate_email'),
]

anki_web/anki_api/models.py
from django.db import models

# Create your models here.

anki_web/decks/forms.py
from django import forms
from .models import Decks


class CreateDeskForm(forms.ModelForm):
    class Meta:
        model = Decks
        fields = [
            'name'
        ]

        widgets = {
            'name': forms.TextInput(attrs={
                'class': "t-text-gray-900 sm:t-text-sm t-rounded-lg t-block t-w-full t-p-2.5",
                'placeholder': 'Название колоды'
            })
        }

anki_web/anki_api/views.py
from rest_framework import generics, status
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView
from anki_web.anki_api.serializers import (
    CardsListSerializer,
    DetailCardSerializer,
    CreateCardSerializer,
    DeckListSerializer,
    StyleListSerializer,
    DeckStudyListSerializer,
    CreateDeckSerializer,
    CardsListStudySerializer,
)
from anki_web.cards.models import Cards
from anki_web.decks.models import Decks
from anki_web.styles.models import Styles
from rest_framework.pagination import PageNumberPagination
from django.db.models import Q, Count
from datetime import date
from random import randint


class StudyCardsAPIListPagination(PageNumberPagination):
    """Пагинация для вывода карточек по одной"""
    page_size = 1
    page_size_query_param = 'page_size'
    max_page_size = 30


class APIListPagination(PageNumberPagination):
    """Простая пагинация при просмотре всех карточек"""
    page_size = 20
    page_size_query_param = 'page_size'
    max_page_size = 30


class CardAPIShowUpdate(generics.RetrieveUpdateAPIView):
    """Вывод информации об выбранной карточке и обновление данной информации"""

    def get_queryset(self):
        queryset = Cards._default_manager.filter(id=self.kwargs.get('pk'))
        return queryset

    serializer_class = DetailCardSerializer
    permission_classes = [
        IsAuthenticated,
    ]


class CardsListAPIView(generics.ListAPIView):
    """Выводит список всех карточек которые
    создал авторизированный пользователь"""
    def get_queryset(self):
        queryset = Cards._default_manager.filter(
            created_by=self.request.user.id
            )
        return queryset

    serializer_class = CardsListSerializer
    pagination_class = APIListPagination
    permission_classes = [
        IsAuthenticated,
    ]


class DecksListAPIView(generics.ListAPIView):
    """Выводит список колод которые создан авторизированный пользователь"""
    def get_queryset(self):
        queryset = Decks._default_manager.filter(
            created_by=self.request.user.id
            )
        return queryset

    serializer_class = DeckListSerializer
    pagination_class = APIListPagination
    permission_classes = [
        IsAuthenticated,
    ]


class StyleListAPIView(APIView):
    """Выводит список имеющихся стилей для вопроса и ответа"""
    def get(self, request, *args, **kwargs):
        styles = Styles._default_manager.all()
        serializer = StyleListSerializer(styles, many=True)
        return Response({'styles': serializer.data})

    permission_classes = [
        IsAuthenticated,
    ]


class CreateCardAPIView(generics.CreateAPIView):
    """Создание карточки"""
    serializer_class = CreateCardSerializer
    permission_classes = [
        IsAuthenticated,
    ]

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(
            data=request.data
        )
        serializer.is_valid(raise_exception=True)
        serializer.save(
            created_by=request.user,
            random_num=randint(1, 2000)
        )
        headers = self.get_success_headers(serializer.data)
        return Response(
            serializer.data,
            status=status.HTTP_201_CREATED,
            headers=headers
            )


class CreateDeckAPIView(generics.CreateAPIView):
    """Создание колоды"""
    serializer_class = CreateDeckSerializer
    permission_classes = [
        IsAuthenticated,
    ]

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(
            data=request.data
        )
        serializer.is_valid(raise_exception=True)
        serializer.save(
            created_by=request.user
        )
        headers = self.get_success_headers(serializer.data)
        return Response(
            serializer.data,
            status=status.HTTP_201_CREATED,
            headers=headers
            )


class CardsFilterListAPIView(generics.ListAPIView):
    """Выводит по одной карточке в выбранной колоде, где дата повторения
    не задана или меньше либо равна текущей дате"""
    def get_queryset(self):
        queryset = Cards._default_manager.filter(
            Q(review_date__isnull=True) | Q(review_date__lte=date.today())
        ).filter(deck=self.kwargs['id'])
        return queryset

    serializer_class = CardsListStudySerializer
    pagination_class = StudyCardsAPIListPagination
    permission_classes = [
        IsAuthenticated,
    ]


class StudyMainView(generics.ListAPIView):
    """Выводит список всех колод,
    где у карточек не задана дата повторения или
    дата повторения меньше либо равна текущей дате
    """
    def get_queryset(self):
        new = Count('cards', filter=Q(cards__review_date__isnull=True))
        old = Count('cards', filter=Q(cards__review_date__lte=date.today()))
        cards = Count('cards')
        queryset = Decks._default_manager.filter(
            created_by=self.request.user.id
        ).values(
            'id', 'name'
        ).annotate(new_cards=new).annotate(old_cards=old).annotate(
            all_cards=cards).filter(all_cards__gt=0)
        return queryset
    serializer_class = DeckStudyListSerializer

    permission_classes = [
        IsAuthenticated,
    ]

anki_web/decks/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import CreateView, ListView, DeleteView
from django.urls import reverse_lazy
from .models import Decks
from anki_web.users.models import Users
from .forms import CreateDeskForm
from anki_web.custom_mixins.mixins import CheckConnectMixin
from django.db.models import Count


class ListDecksView(ListView):
    model = Decks
    template_name = 'decks/decks.html'
    context_object_name = 'decks'

    def get_queryset(self):
        queryset = self.model._default_manager.filter(
            created_by=self.request.user.id
        ).values('id', 'name').annotate(count=Count('cards'))
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Колоды'
        return context


class CreateDeckView(SuccessMessageMixin, CreateView):
    model = Decks
    form_class = CreateDeskForm
    template_name = 'form.html'
    success_url = reverse_lazy('decks:decks')
    success_message = 'Колода успешно создана'

    def form_valid(self, form):
        form.instance.created_by = Users.objects.get(pk=self.request.user.id)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['text_button'] = 'Добавить'
        return context


class DeleteDeckView(SuccessMessageMixin, CheckConnectMixin, DeleteView):
    model = Decks
    template_name = 'delete.html'
    success_url = reverse_lazy('decks:decks')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['text_button'] = 'Удалить'
        return context

anki_web/styles/views.py
from django.shortcuts import render

# Create your views here.

anki_web/users/views.py
from django.views import generic
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage
from django.contrib.auth.tokens import default_token_generator
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Users
from .forms import CreateUserForm, UpdateUserForm, ChangePasswordForm, AddEmailForm


class CreateUserView(generic.CreateView):
    model = Users
    form_class = CreateUserForm
    template_name = 'registration.html'
    success_url = reverse_lazy('login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['text_button'] = 'Зарегистрироваться'
        return context


@login_required
def show_user(request):
    username = request.user.username
    date_joined = request.user.date_joined
    cards = request.user.cards_set.count()
    decks = request.user.decks_set.count()
    return render(
        request,
        'users/profile.html',
        context={
            'username': username,
            'date_joined': date_joined,
            'cards': cards,
            'decks': decks
        }
    )


class UpdateUserInfoView(generic.UpdateView):
    model = Users
    form_class = UpdateUserForm
    template_name = 'form.html'
    success_url = reverse_lazy('show_user')
    success_message = 'Пользователь был успешно обновлен'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['text_button'] = 'Обновить'
        return context


def change_password(request):
    if request.method == 'GET':
        form = ChangePasswordForm(user=request.user)
        return render(
            request,
            template_name='form.html',
            context={
                'form': form,
                'text_button': 'Изменить пароль'
            }
        )
    elif request.method == 'POST':
        form = ChangePasswordForm(user=request.user, data=request.POST)
        if form.is_valid():
            print('valid')
            form.save()
            messages.success(request, 'Пароль успешно изменен')
            return redirect('login')
        else:
            print('invalid')
            print(form.errors)
            return render(request, 'form.html', {
                'form': form,
                'text_button': 'Изменить пароль'
            })


class AddEmailView(generic.UpdateView):
    model = Users
    form_class = AddEmailForm
    template_name = 'form.html'

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        new_email = self.request.POST.get('email')
        if self.request.user.email == new_email and self.request.user.email_is_active:
            messages.info(self.request, message=f'Почта {new_email} уже подтверждена')
            return redirect(reverse_lazy('add_email', kwargs={'pk': self.object.id}))
        user = form.save(commit=False)
        user.email_is_active = False
        user.save()
        
        current_site = get_current_site(self.request)
        mail_subject = 'Activation link has been sent to your email id'
        mail_body = render_to_string('users/confirm_email.html',
                                     {
                                         'user': self.object,
                                         'domain': current_site.domain,
                                         'uid': urlsafe_base64_encode(force_bytes(self.object.pk)),
                                         'token': default_token_generator.make_token(user=self.object)
                                     })
        to_email = form.cleaned_data.get('email')
        email = EmailMessage(
            mail_subject, mail_body, to=[to_email]
        )
        email.send()
        messages.info(self.request, message='Please confirm your email address to complete the registration')
        return redirect('show_user')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.email:
            context['text_button'] = 'Обновить'
        else:
            context['text_button'] = 'Добавить почту'
        return context


def activate_email(request, uidb64, token):  
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))  
        user = Users.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Users.DoesNotExist):
        user = None
    print(default_token_generator.check_token(user, token))
    if user is not None and default_token_generator.check_token(user, token):
        user.email_is_active = True
        user.save()
        messages.success(request, message='Thank you for your email confirmation. Now you can login your account.')
        return redirect('show_user')
    else:
        messages.error(request, message='Activation link is invalid!')
        return redirect('show_user')

anki_web/templates/cards/cards.html
{% extends 'base.html' %}
{% load card_extras %}
{% block title %}
{{ title }}
{% endblock %}
{% block content %}
<table class="t-w-full t-border-collapse t-text-sm">
    <thead>
        <tr class="t-text-left">
            <th></th>
            <th>Вопрос</th>
            <th>Дата создания</th>
            <th class="t-pl-2">Следующее повторение</th>
        </tr>
    </thead>
    <tbody>
        {% if deck_id %}
        <form action="{% url 'cards:select' %}" method="post">
            {% csrf_token %}
            {% for card in cards %}
            <tr class=" odd:t-bg-gray-100">
                <td class="t-py-5 t-px-5">
                    <input type="checkbox" name="select" value="{{ card.id }}">
                </td>
                <td>
                    <a class="hover:t-underline" href="{% url 'cards:show_card' pk=card.id %}">
                        {{ card.question | truncatechars:19 }}</a>
                </td>
                <td>
                    {{ card.created_at | date:"Y-m-d" }}
                </td>
                <td>
                    {{ card.review_date | date:"Y-m-d" }}
                </td>
            </tr>
            {% endfor %}
            <div class="t-flex t-flex-row t-justify-between t-text-xs">
                <div class="t-flex t-flex-row t-gap-3 t-items-center">
                    <input
                        class="t-border t-rounded-lg t-px-2 t-py-1.5 t-text-center t-text-xs t-text-red-600 t-border-red-600 hover:t-bg-red-600 hover:t-text-white"
                        type="submit" onclick="delete_confirm(event)" value="Удалить">
                    <a class="t-border t-rounded-lg t-px-2 t-py-1.5 t-text-center t-text-xs t-text-red-600 t-border-red-600 hover:t-bg-red-600 hover:t-text-white"
                        href="{% url 'decks:delete_all' pk=deck_id%}">Удалить все</a>
                </div>
                <div class="">
                    <a class="t-border t-rounded-lg t-px-2 t-py-1.5 t-text-center t-text-xs t-text-green-600 t-border-green-600 hover:t-bg-green-600 hover:t-text-white"
                        href="{% url 'decks:download' pk=deck_id%}">Скачать</a>
                </div>
            </div>
        </form>
        {% else %}
        <form action="{% url 'cards:select' %}" method="post">
            {% csrf_token %}
            {% for card in cards %}
            <tr class=" odd:t-bg-gray-100">
                <td class="t-py-5 t-px-5">
                    <input type="checkbox" name="select" value="{{ card.id }}">
                </td>
                <td>
                    <a class="hover:t-underline" href="{% url 'cards:show_card' pk=card.id %}">
                        {{ card.question | truncatechars:19 }}</a>
                </td>
                <td>
                    {{ card.created_at | date:"Y-m-d" }}
                </td>
                <td>
                    {{ card.review_date | date:"Y-m-d" }}
                </td>
            </tr>
            {% endfor %}
            <div class="t-flex t-flex-row t-justify-between t-text-xs">
                <div class="t-flex t-flex-row t-gap-3 t-items-center">
                    <input
                        class="t-border t-rounded-lg t-px-2 t-py-1.5 t-text-center t-text-xs t-text-red-600 t-border-red-600 hover:t-bg-red-600 hover:t-text-white"
                        type="submit" onclick="delete_confirm(event)" value="Удалить">
                    <a class="t-border t-rounded-lg t-px-2 t-py-1.5 t-text-center t-text-xs t-text-red-600 t-border-red-600 hover:t-bg-red-600 hover:t-text-white"
                        href="{% url 'cards:delete_all' %}">Удалить все</a>
                </div>
                <div class="">
                    <a class="t-border t-rounded-lg t-px-2 t-py-1.5 t-text-center t-text-xs t-text-green-600 t-border-green-600 hover:t-bg-green-600 hover:t-text-white"
                        href="{% url 'cards:download' %}">Скачать</a>
                </div>
            </div>
            {% endif %}
        </form>
    </tbody>
</table>
<ul class="t-flex t-flex-row t-list-none t-mb-5 t-items-center t-justify-center t-gap-3 t-w-full t-text-blue-500">
    {% if page_obj.has_previous %}
    {% if page_obj.number|add:'-3' > 1 %}
    <li class="page-item">
        <a class="page-link" href="?page=1">1</a>
    </li>
    {% endif %}
    {% if page_obj.number|add:'-3' >= 3 %}
    <li class="page-item pagination__item--dots">
        <a href="?page={{ page_obj.previous_page_number|add:'-3' }}">
            <span class="page-link">• • •</span>
        </a>
    </li>
    {% endif %}
    {% endif %}
    {% if paginator.page_range|length > 1 %}
    {% for i in paginator.page_range %}
    {% if page_obj.number == i %}
    <li class="t-underline t-font-bold">
        <a class="page-link" href="#">{{ i }}</a>
    </li>
    {% elif i > page_obj.number|add:'-4' and i < page_obj.number|add:'4' %} <li class="page-item">
        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
        {% endif %}
        {% endfor %}
        {% endif %}
        {% if page_obj.has_next %}
        {% if page_obj.number|add:'4' < page_obj.paginator.num_pages %} <li class="page-item pagination__item--dots">
            <a href="?page={{ page_obj.next_page_number|add:'3' }}">
                <span class="page-link">• • •</span>
            </a>
            </li>
            {% endif %}
            {% if page_obj.number|add:'3' < page_obj.paginator.num_pages %} <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                    {{ page_obj.paginator.num_pages }}
                </a>
                </li>
                {% endif %}
                {% endif %}
</ul>
{% endblock %}

anki_web/templates/cards/cards_learn.html
{% extends 'base.html' %}
{% load card_extras %}
{% block content %}
{% if not card %}
<h4 class="t-text-center t-text-xl">На сегодня все!</h4>
{% else %}
<div class="t-flex t-flex-col t-gap-2">
    <div class="t-flex t-flex-row t-justify-between t-w-full t-text-[12px]">
        <p class="display-6 text-primary text-left">Осталось {{ count.count }} карточек</p>
        <a class="t-text-blue-600 hover:t-underline" href="{% url 'cards:update' pk=card.id %}">
            Редактировать
        </a>
    </div>
    <div class="t-flex t-flex-col t-border t-text-center t-items-center t-py-5 t-rounded-xl t-gap-5">
        <h4 class="t-text-sm">Вопрос:</h4>
        {% if card.question_type == 'md' %}
        <p class="t-px-2">{{ card.question | convert_markdown | safe }}</p>
        {% elif card.question_type == 'html' %}
        <p class="t-px-2">
            {% autoescape off %}
            {{ card.question }}
            {% endautoescape %}
        </p>
        {% elif card.question_type == 'text' %}
        <p class="t-px-2">
            {% autoescape on %}
            {{ card.question }}
            {% endautoescape %}
        </p>
        {% endif %}
        {% if card.style == 2 %}
        <form class="t-text-sm t-flex t-flex-col t-items-center t-w-full t-px-4"
            action="{% url 'decks:answer' card_id=card.id %}" method="post">
            {% csrf_token %}
            <textarea class="t-resize-none t-border-gray-300 t-rounded-lg t-mb-4 t-w-full" name="answer"></textarea>
            <input
                class="t-text-white t-bg-blue-600 hover:t-bg-blue-700 focus:t-ring-4 focus:t-outline-none focus:t-ring-blue-300 t-font-medium t-rounded-lg t-text-sm t-px-5 t-py-2.5 t-text-center t-w-5/12"
                type="submit" value="Ответ">
        </form>
        {% else %}
        <a class=" t-text-white t-bg-blue-600 hover:t-bg-blue-700 focus:t-ring-4 focus:t-outline-none focus:t-ring-blue-300 t-font-medium t-rounded-lg t-text-sm t-px-5 t-py-2.5 t-text-center"
            href="{% url 'decks:answer' card_id=card.id %}">Ответ</a>
        {% endif %}
    </div>
</div>
{% endif %}
{% endblock %}

anki_web/templates/cards/show_card.html
{% extends 'base.html' %}
{% load card_extras %}
{% load static %}
{% block content %}
<div class="t-flex t-flex-row t-mx-3 t-gap-2 t-justify-between">
    <a class="t-text-yellow-600 hover:t-underline t-text-sm"
        href="{% url 'cards:update' pk=card.id %}">Редактировать</a>
    <a class="t-text-red-600 hover:t-underline t-text-sm" href="{% url 'cards:delete' pk=card.id %}">Удалить</a>
</div>
<div class="t-flex t-flex-col t-gap-5 t-border t-rounded-xl t-py-5">

    <div class="t-flex t-flex-row t-gap-2 t-px-2 t-justify-center">
        <h4 class="t-text-gray-400">Вопрос:</h4>
        {% if card.question_type == 'md' %}
        <p>{{ card.question | convert_markdown | safe }}</p>
        {% elif card.question_type == 'html' %}
        <p>
            {% autoescape off %}
            {{ card.question }}
            {% endautoescape %}
        </p>
        {% elif card.question_type == 'text' %}
        <p>
            {% autoescape on %}
            {{ card.question }}
            {% endautoescape %}
        </p>
        {% endif %}
    </div>
    <hr>
    <div class="t-flex t-flex-row t-gap-2 t-px-2 t-justify-center">
        <h4 class="t-text-gray-400">Ответ:</h4>
        {% if card.answer_type == 'md' %}
        <p>{{ card.answer | convert_markdown | safe }}</p>
        {% elif card.answer_type == 'html' %}
        <p>
            {% autoescape off %}
            {{ card.answer }}
            {% endautoescape %}
        </p>
        {% elif card.answer_type == 'text' %}
        <p>
            {% autoescape on %}
            {{ card.answer }}
            {% endautoescape %}
        </p>
        {% endif %}
    </div>
    <div class="t-flex t-flex-row t-justify-between t-px-10">
        <div class="t-flex t-flex-row t-gap-2">
            <div class="t-text-gray-400">ID:</div>
            <div class="">{{ card.id }}</div>
        </div>
        <div class="t-flex t-flex-row t-gap-2">
            <div class="t-text-gray-400">Стиль карточки:</div>
            <div class="">{{ card.style }}</div>
        </div>
    </div>
    <div class="t-flex t-flex-row t-justify-between t-px-2 sm:t-px-10">
        <div class="t-flex t-flex-row t-gap-2">
            <div class="t-text-gray-400">Дата создания:</div>
            <div class="">{{ card.created_at | date:"Y-m-d" }}</div>
        </div>
        <div class="t-flex t-flex-row t-gap-2">
            <div class="t-text-gray-400">Дата повторения:</div>
            {% if card.review_date %}
            <div class="">{{ card.review_date | date:"Y-m-d"}}</div>
            {% else %}
            <div class="">нет даты</div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

anki_web/templates/cards/upload.html
{% extends 'base.html' %}
{% block content %}
<div class=" t-bg-white t-rounded-lg t-shadow t-w-[400px] t-mx-auto t-mb-4">
    <form class="t-flex t-flex-col t-gap-2 t-p-5" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input
            class="t-text-white t-w-full t-bg-blue-600 hover:t-bg-blue-700 focus:t-ring-4 focus:t-outline-none focus:t-ring-blue-300 t-font-medium t-rounded-lg t-text-sm t-px-5 t-py-2.5 t-text-center"
            type="submit" value="Загрузить">
    </form>
</div>
{% endblock %}